In [1]:
import pandas as pd
import numpy as np
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [12]:
data_df = pd.read_csv("../Data/data_with_industry_codes.csv")
questions_df = pd.read_csv("../Data/questions.csv")
questions_df = questions_df.filter(['questions_id','questions_title','questions_date_added','questions_body'])
best_answer_df = pd.merge(data_df, questions_df, on="questions_id")
best_answer_df = best_answer_df.drop(columns=['Unnamed: 0'])
# best_answer_df_short = best_answer_df.head(10)
# best_answer_df_short

best_answer_df

questions_id                        answers_id  \
0      f6b9ca94aed04ba28256492708e74f60  7640a6e5d5224c8681cc58de860858f4   
1      00f9376f9c864631bc970f3a49c6aa08  26e01bf820d84de4952d5fe04aab62e1   
2      08a105aaa206418294d7bdf291e0235d  0f5615fcffb349d9b07e9a714d0573dc   
3      2c5bd5eb628245acb868c81fefcfe5e0  281c2557f0154dde984707e40100b8b4   
4      2f2378acab3f444199ee2b69d2d3626f  63b7a06323ee4d578a37cf780debfa58   
5      333464d7484b43e3866e86096bc4ddb9  683b200ad5014e84a441db677f990d75   
6      34feb9980e7742109adfab22828329f0  1ddd5ce4c80c4523bc055f7f4b66d4a1   
7      3738884893914f98bc9b6274248700fc  765f4a46b76c4c3496cbc2de6faf8c2d   
8      5bd585028efe49f4b89701b84e6fbe8c  d0388adf192c4683a1d9a079f88fbd52   
9      60824610a30541eda9e1e7ed6b7b3599  d27157b184a54761ab51f79fab878b0c   
10     700172696b9b48859d4a9855f1878ac5  9522aa09989043b88319bd1b2080b1bf   
11     71a6ab49a9444c60b45c458b57fa5960  90826bc9dd574074a5a56dffcb021d71   
12     749c5632a7c34f3f86590c9f8a1da2db  63118ff15bb142caba765d30cd2e71b0   
13     82acf6d8608b4743848d0c8c4e5c610b  ae8d6e375f804c698c324def1a3bf4f9   
14     8ce7dde9cbe04940bbcdf4577e7296f3  2b0a9b3c1f5c48168696ce1a614582c3   
15     9d211b99e17c46fbbaca03dc6b43f1c4  5d670d5f8700402ab56bae609b06d02d   
16     9dcea61327f545f7a0a3f75365477555  3ac551fd27224579944227533762164e   
17     a7bc96f56e0742a9a39bbb91d118b465  43aee8f10fb14ae2a235a95dbc05dfc4   
18     b3534776e3854e8bb73d8a1b1be3511f  f46ad30f5220449f9ac36f66f49ba310   
19     c9c6a69320874a0ca994a41073ca6a6b  37becf313a4a4526a0bb0c3d67d78b75   
20     ca209b4e19064d8e9834b3ca1a3f5361  7d1a41e5ef48410fa7ff647a4bf87eed   
21     d98717b213984ed1a715bd88367d6258  a836064f4eaf491eaeb4142e8d4cd752   
22     dfd33a7465f540989adf7795cbedb712  429ecea83a574e84affba375ce6da5ef   
23     e978b437413048c183e3cb556f90a878  6d823a750e294c75b10fafbbbaf19855   
24     fdce59131eb74b449fa20a1ceb898149  97eba893d7084b798575e13e39f774ae   
25     0025b917219c4a24ba5fe260ca66ca98  f9390f8f2e4a40f9876ba0d81604734a   
26     02d4ff95d2eb4bee881f6320a99dbc0b  ba39d1b1eb954cf2b26e3e13725ba6ec   
27     042bbf8655164b5ea67db345942fa4d4  ebb42a9209ef4c269a96986c8343cbbb   
28     0914db8647f14ed18ab2a7b321d0b81d  ca4491e34b144cf480fb854751d4c8ca   
29     09c872ce237842c1885d7f1584c6bdf5  a0ab7598b93e4f7bb13dab64d5708265   
...                                 ...                               ...   
22424  ff2e37a4ee3542e8968463b3499f648d  ff714f8ac3c044c785a5fe5a0a5c9249   
22425  081c9289dd5e49258e4224e1fe3e4b63  eee6a4fa0ce040ddaf60568aefa84d8a   
22426  8af30195ce3646729174a7d0a3ceaf71  153658272b224da1a0e7d514b360e1f2   
22427  23d3812ef6b24b279629b769105d09eb  d3d8c484e7a74532aeac1921f73f67dd   
22428  0c3bbf6f7b714e35868b7d26dc74af98  20bc5ecbb0294047a39bd93ffea4e22b   
22429  76d859078179418990bda99f28c3f054  a4936c692b8f47c3a35259e09662973e   
22430  e8c8ed32802b4090b5865dd3c2c3f42a  c75837f01ecd4f1cba57b0624a18733f   
22431  7b69abaa38e2491d935b66ed7953c326  e0ae91bc3ed343729d655e0daa6a920a   
22432  ea310e9eca8d4cd5991ecc6c047afd30  8fc97bbeb33d429cb166fbbdd2bcf13b   
22433  993e65ddbfd24ea2a133d8d96a7b6ceb  5d91c2d66e8448d088b4941869af2d8b   
22434  22d856b36b0144049c41c233da70337b  4c2e830bf8714e098181461b13b153dd   
22435  a7931d4e538f4a558c4f59e73e96b887  cc36ac9c07404717b7565a81143aa872   
22436  cdde8aaf6911492685982a4c728a9dff  37e86d94cf2e4c30adc4bc91d6a8f1ff   
22437  158bc55a058a4a5e9c4ee861c24e80d7  2ebfe053987c4a25a70acc4218d1f457   
22438  f4507b9a329743dc877b444364713bcd  afcc71704873454cb611260546bf53ff   
22439  f85e9591309b42fcb4fe7cc5b56fa346  a9f83ab87a3b4b26b9055122a0d5d5bc   
22440  03fd4382fd09420184827e522b0ae3b3  0c2600cbe13c4fbe8dbe3544fcff39af   
22441  2cca2904d3e24037b99b156009521955  30e6b58bf2664cc3befbf7f2f5d6324a   
22442  5aaac422880a434f85ad47b11557eddf  78ab159ab1c846c99435c05e2e21f691   
22443  b7310723d6bc4db3b3f30317dbd57598  b50f9a825ede4641972e8e8da2976fc1   
22444  d4b10756aac1424c

In [13]:
from cypher import encode
from datetime import datetime

In [14]:
best_answer_df['indexed'] = best_answer_df.apply(lambda x: encode(x['questions_title'], x['questions_body']), axis=1)

In [15]:
ba_df = best_answer_df
ba_df.dtypes

questions_id              object
answers_id                object
questions_id.1            object
professionals_industry    object
industry_codes             int64
questions_title           object
questions_date_added      object
questions_body            object
indexed                   object
dtype: object

In [16]:
# ba_df['industry_codes'] = ba_df['industry_codes'].astype(int)
# ba_df.dtypes

In [17]:
indexed_padded = pad_sequences(best_answer_df['indexed'], value=0, padding='post', maxlen=50)

In [18]:
indexed_padded[666]

array([    1,  9913,     2, 13342, 14952, 14040, 17348, 16978, 17266,
       18305, 18045, 18103, 18429, 17447, 18219, 18422, 14040, 16660,
       17578, 18193, 17266, 10051, 17531,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0])

In [19]:
import keras
import tensorflow as tf

In [20]:
from sklearn.model_selection import train_test_split

X=indexed_padded
y = best_answer_df["industry_codes"]

print(X.shape, y.shape)

(22454, 50) (22454,)


In [21]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5)

In [23]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_test_scaled[100]

array([0.        , 0.81018544, 0.        , 0.87210119, 0.96372777,
       0.99859452, 0.96399805, 0.96864695, 0.79842154, 0.96399805,
       0.87210119, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [24]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
# label_encoder.fit(y_test)
encoded_y_train = label_encoder.transform(y_train)
# encoded_y_test = label_encoder.transform(y_test)
encoded_y_train

array([293, 473, 267, ..., 267, 148, 380], dtype=int64)

In [25]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
# y_test_categorical = to_categorical(encoded_y_test)

y_train_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# input shape is the vocabulary count used for the movie reviews (10,000 words)
# vocab_size = 10000
# model = keras.Sequential()
# model.add(keras.layers.Embedding(vocab_size, 50))
# model.add(keras.layers.GlobalAveragePooling1D())
# model.add(keras.layers.Dense(1, activation=tf.nn.relu))
# model.add(keras.layers.Dense(821, activation=tf.nn.relu))
# model.summary()

In [37]:
# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=50))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=75, activation='relu'))
model.add(Dense(units=821, activation='sigmoid'))

In [38]:
# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [39]:
X_train_scaled.dtype

dtype('float64')

In [40]:
y_train_categorical.dtype

dtype('float32')

In [41]:
# Fit the model to the training data
model.fit(
    X_train_scaled,
    encoded_y_train,
    epochs=1000,
    shuffle=True,
    verbose=2
)

Epoch 1/1000
 - 1s - loss: 4.7699 - acc: 0.0702
Epoch 2/1000
 - 1s - loss: 4.4347 - acc: 0.1017
Epoch 3/1000
 - 1s - loss: 4.3964 - acc: 0.1017
Epoch 4/1000
 - 1s - loss: 4.3708 - acc: 0.1017
Epoch 5/1000
 - 1s - loss: 4.3523 - acc: 0.1017
Epoch 6/1000
 - 1s - loss: 4.3341 - acc: 0.1017
Epoch 7/1000
 - 1s - loss: 4.3159 - acc: 0.1017
Epoch 8/1000
 - 1s - loss: 4.3034 - acc: 0.1017
Epoch 9/1000
 - 1s - loss: 4.2855 - acc: 0.1017
Epoch 10/1000
 - 1s - loss: 4.2704 - acc: 0.1017
Epoch 11/1000
 - 1s - loss: 4.2517 - acc: 0.1017
Epoch 12/1000
 - 1s - loss: 4.2341 - acc: 0.1017
Epoch 13/1000
 - 1s - loss: 4.2163 - acc: 0.1017
Epoch 14/1000
 - 1s - loss: 4.1961 - acc: 0.1017
Epoch 15/1000
 - 1s - loss: 4.1713 - acc: 0.1017
Epoch 16/1000
 - 1s - loss: 4.1453 - acc: 0.1017
Epoch 17/1000
 - 1s - loss: 4.1236 - acc: 0.1017
Epoch 18/1000
 - 1s - loss: 4.1005 - acc: 0.1017
Epoch 19/1000
 - 1s - loss: 4.0748 - acc: 0.1017
Epoch 20/1000
 - 1s - loss: 4.0466 - acc: 0.1017
Epoch 21/1000
 - 1s - loss: 4

 - 1s - loss: 2.2855 - acc: 0.3847
Epoch 168/1000
 - 1s - loss: 2.2824 - acc: 0.3871
Epoch 169/1000
 - 1s - loss: 2.2686 - acc: 0.3927
Epoch 170/1000
 - 1s - loss: 2.2782 - acc: 0.3860
Epoch 171/1000
 - 1s - loss: 2.2765 - acc: 0.3877
Epoch 172/1000
 - 1s - loss: 2.2591 - acc: 0.3917
Epoch 173/1000
 - 1s - loss: 2.2558 - acc: 0.3922
Epoch 174/1000
 - 1s - loss: 2.2524 - acc: 0.3977
Epoch 175/1000
 - 1s - loss: 2.2443 - acc: 0.3953
Epoch 176/1000
 - 1s - loss: 2.2489 - acc: 0.3979
Epoch 177/1000
 - 1s - loss: 2.2414 - acc: 0.3987
Epoch 178/1000
 - 1s - loss: 2.2301 - acc: 0.4041
Epoch 179/1000
 - 1s - loss: 2.2352 - acc: 0.3971
Epoch 180/1000
 - 1s - loss: 2.2183 - acc: 0.4060
Epoch 181/1000
 - 1s - loss: 2.2222 - acc: 0.4032
Epoch 182/1000
 - 1s - loss: 2.2137 - acc: 0.4034
Epoch 183/1000
 - 1s - loss: 2.2082 - acc: 0.4050
Epoch 184/1000
 - 1s - loss: 2.2002 - acc: 0.4070
Epoch 185/1000
 - 1s - loss: 2.1964 - acc: 0.4128
Epoch 186/1000
 - 1s - loss: 2.1982 - acc: 0.4090
Epoch 187/1000


 - 1s - loss: 1.7692 - acc: 0.5108
Epoch 332/1000
 - 1s - loss: 1.7845 - acc: 0.5065
Epoch 333/1000
 - 1s - loss: 1.7479 - acc: 0.5175
Epoch 334/1000
 - 1s - loss: 1.7759 - acc: 0.5114
Epoch 335/1000
 - 1s - loss: 1.7530 - acc: 0.5205
Epoch 336/1000
 - 1s - loss: 1.7469 - acc: 0.5167
Epoch 337/1000
 - 1s - loss: 1.7688 - acc: 0.5079
Epoch 338/1000
 - 1s - loss: 1.7677 - acc: 0.5121
Epoch 339/1000
 - 1s - loss: 1.7505 - acc: 0.5149
Epoch 340/1000
 - 1s - loss: 1.7469 - acc: 0.5179
Epoch 341/1000
 - 1s - loss: 1.7554 - acc: 0.5129
Epoch 342/1000
 - 1s - loss: 1.7402 - acc: 0.5220
Epoch 343/1000
 - 1s - loss: 1.7429 - acc: 0.5194
Epoch 344/1000
 - 1s - loss: 1.7841 - acc: 0.5079
Epoch 345/1000
 - 1s - loss: 1.7430 - acc: 0.5105
Epoch 346/1000
 - 1s - loss: 1.7229 - acc: 0.5246
Epoch 347/1000
 - 1s - loss: 1.7250 - acc: 0.5279
Epoch 348/1000
 - 1s - loss: 1.7421 - acc: 0.5171
Epoch 349/1000
 - 1s - loss: 1.7310 - acc: 0.5211
Epoch 350/1000
 - 1s - loss: 1.7563 - acc: 0.5059
Epoch 351/1000


 - 1s - loss: 1.5055 - acc: 0.5789
Epoch 496/1000
 - 1s - loss: 1.5215 - acc: 0.5713
Epoch 497/1000
 - 1s - loss: 1.5253 - acc: 0.5681
Epoch 498/1000
 - 1s - loss: 1.5026 - acc: 0.5802
Epoch 499/1000
 - 1s - loss: 1.5426 - acc: 0.5638
Epoch 500/1000
 - 1s - loss: 1.5196 - acc: 0.5744
Epoch 501/1000
 - 1s - loss: 1.5391 - acc: 0.5654
Epoch 502/1000
 - 1s - loss: 1.5592 - acc: 0.5628
Epoch 503/1000
 - 1s - loss: 1.5112 - acc: 0.5795
Epoch 504/1000
 - 1s - loss: 1.5195 - acc: 0.5749
Epoch 505/1000
 - 1s - loss: 1.4985 - acc: 0.5843
Epoch 506/1000
 - 1s - loss: 1.4985 - acc: 0.5769
Epoch 507/1000
 - 1s - loss: 1.5144 - acc: 0.5717
Epoch 508/1000
 - 1s - loss: 1.5048 - acc: 0.5774
Epoch 509/1000
 - 1s - loss: 1.5111 - acc: 0.5743
Epoch 510/1000
 - 1s - loss: 1.5201 - acc: 0.5680
Epoch 511/1000
 - 1s - loss: 1.5375 - acc: 0.5700
Epoch 512/1000
 - 1s - loss: 1.4978 - acc: 0.5798
Epoch 513/1000
 - 1s - loss: 1.5106 - acc: 0.5749
Epoch 514/1000
 - 1s - loss: 1.5254 - acc: 0.5676
Epoch 515/1000


 - 1s - loss: 1.4080 - acc: 0.6010
Epoch 660/1000
 - 1s - loss: 1.3926 - acc: 0.6041
Epoch 661/1000
 - 1s - loss: 1.4167 - acc: 0.5956
Epoch 662/1000
 - 1s - loss: 1.4026 - acc: 0.5985
Epoch 663/1000
 - 1s - loss: 1.3965 - acc: 0.5990
Epoch 664/1000
 - 1s - loss: 1.4073 - acc: 0.6009
Epoch 665/1000
 - 1s - loss: 1.3587 - acc: 0.6170
Epoch 666/1000
 - 1s - loss: 1.3703 - acc: 0.6109
Epoch 667/1000
 - 1s - loss: 1.3994 - acc: 0.6014
Epoch 668/1000
 - 1s - loss: 1.4347 - acc: 0.5881
Epoch 669/1000
 - 1s - loss: 1.4089 - acc: 0.5989
Epoch 670/1000
 - 1s - loss: 1.3921 - acc: 0.6027
Epoch 671/1000
 - 1s - loss: 1.3894 - acc: 0.6073
Epoch 672/1000
 - 1s - loss: 1.3689 - acc: 0.6109
Epoch 673/1000
 - 1s - loss: 1.3711 - acc: 0.6130
Epoch 674/1000
 - 1s - loss: 1.3972 - acc: 0.6047
Epoch 675/1000
 - 1s - loss: 1.3936 - acc: 0.6032
Epoch 676/1000
 - 1s - loss: 1.4167 - acc: 0.5945
Epoch 677/1000
 - 1s - loss: 1.4044 - acc: 0.6024
Epoch 678/1000
 - 1s - loss: 1.3774 - acc: 0.6076
Epoch 679/1000


 - 1s - loss: 1.3422 - acc: 0.6204
Epoch 824/1000
 - 1s - loss: 1.2908 - acc: 0.6301
Epoch 825/1000
 - 1s - loss: 1.3346 - acc: 0.6195
Epoch 826/1000
 - 1s - loss: 1.3268 - acc: 0.6233
Epoch 827/1000
 - 1s - loss: 1.3246 - acc: 0.6189
Epoch 828/1000
 - 1s - loss: 1.3124 - acc: 0.6236
Epoch 829/1000
 - 1s - loss: 1.3316 - acc: 0.6179
Epoch 830/1000
 - 1s - loss: 1.2881 - acc: 0.6340
Epoch 831/1000
 - 1s - loss: 1.3100 - acc: 0.6252
Epoch 832/1000
 - 1s - loss: 1.3386 - acc: 0.6200
Epoch 833/1000
 - 1s - loss: 1.4472 - acc: 0.5837
Epoch 834/1000
 - 1s - loss: 1.3068 - acc: 0.6265
Epoch 835/1000
 - 1s - loss: 1.2673 - acc: 0.6389
Epoch 836/1000
 - 1s - loss: 1.3157 - acc: 0.6238
Epoch 837/1000
 - 1s - loss: 1.3258 - acc: 0.6145
Epoch 838/1000
 - 1s - loss: 1.2876 - acc: 0.6334
Epoch 839/1000
 - 1s - loss: 1.3150 - acc: 0.6255
Epoch 840/1000
 - 1s - loss: 1.3189 - acc: 0.6190
Epoch 841/1000
 - 1s - loss: 1.2959 - acc: 0.6277
Epoch 842/1000
 - 1s - loss: 1.3210 - acc: 0.6199
Epoch 843/1000


 - 1s - loss: 1.2595 - acc: 0.6373
Epoch 988/1000
 - 1s - loss: 1.2082 - acc: 0.6566
Epoch 989/1000
 - 1s - loss: 1.2265 - acc: 0.6492
Epoch 990/1000
 - 2s - loss: 1.2596 - acc: 0.6366
Epoch 991/1000
 - 1s - loss: 1.2653 - acc: 0.6355
Epoch 992/1000
 - 1s - loss: 1.2348 - acc: 0.6451
Epoch 993/1000
 - 1s - loss: 1.2485 - acc: 0.6369
Epoch 994/1000
 - 2s - loss: 1.2663 - acc: 0.6332
Epoch 995/1000
 - 1s - loss: 1.3129 - acc: 0.6255
Epoch 996/1000
 - 1s - loss: 1.2092 - acc: 0.6503
Epoch 997/1000
 - 1s - loss: 1.2537 - acc: 0.6345
Epoch 998/1000
 - 1s - loss: 1.2360 - acc: 0.6463
Epoch 999/1000
 - 1s - loss: 1.2964 - acc: 0.6218
Epoch 1000/1000
 - 1s - loss: 1.2727 - acc: 0.6366


In [42]:
model_loss, model_accuracy = model.evaluate(
    X_train_scaled, encoded_y_train, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 1s - loss: 1.2910 - acc: 0.6322
Normal Neural Network - Loss: 1.2909903281665374, Accuracy: 0.6322258710861206


In [43]:
# Save the model
model.save("third_model.h5")

In [44]:
from tensorflow.keras.models import load_model

model2 = load_model('third_model.h5')

model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 100)               5100      
_________________________________________________________________
dense_11 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_12 (Dense)             (None, 75)                7575      
_________________________________________________________________
dense_13 (Dense)             (None, 821)               62396     
Total params: 85,171
Trainable params: 85,171
Non-trainable params: 0
_________________________________________________________________
